services:

  server:
    build: ./server
    container_name: rcssserver
    networks:
      - robocup_net
    command: ./rcssserver server::port=6000 server::auto_mode=true

  team_left:
    build:
      context: ..
      dockerfile: docker/agents/Dockerfile
    container_name: team_left
    environment:
      - SERVER_IP=rcssserver
      - SERVER_PORT=6000
      - TEAM=left
      - NUM_AGENTS=11
    depends_on:
      - server
    networks:
      - robocup_net

  team_right:
    build:
      context: ..
      dockerfile: docker/agents/Dockerfile
    container_name: team_right
    environment:
      - SERVER_IP=rcssserver
      - SERVER_PORT=6000
      - TEAM=right
      - NUM_AGENTS=11
    depends_on:
      - server
    networks:
      - robocup_net
  monitor:
    build: ./monitor
    container_name: rcssmonitor
    ports:
      - "5900:5900"
    networks:
      - robocup_net
    depends_on:
      - server

networks:
  robocup_net:
    driver: bridge